"""Comprehensive update for orders and recipes

Revision ID: 1a80552131a1
Revises: 485b7266efba
Create Date: 2026-01-28 18:18:44.464357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a80552131a1'
down_revision = '485b7266efba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_date', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('delivery_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               nullable=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_orders_product_id_recipes'), 'recipes', ['product_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ingredient_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('material_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('labor_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_cost', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_per_unit', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('profit_margin', sa.Float(), nullable=True))
        batch_op.alter_column('selling_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_recipes_name'), ['name'])
        batch_op.drop_column('labor_hours')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_users_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_users_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_users_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_users_email'), type_='unique')

    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('labor_hours', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint(batch_op.f('uq_recipes_name'), type_='unique')
        batch_op.alter_column('selling_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('profit_margin')
        batch_op.drop_column('profit_per_unit')
        batch_op.drop_column('total_cost')
        batch_op.drop_column('labor_cost')
        batch_op.drop_column('material_cost')
        batch_op.drop_column('ingredient_count')
        batch_op.drop_column('ingredients_json')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_orders_product_id_recipes'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('delivery_mode',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('customer_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('notes')
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('customer_address')
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('order_date')

    # ### end Alembic commands ###
